dnf install libogg
dnf install passwd
dnf install jimtcl
dnf install lsof
dnf install dleyna-server
dnf install perl-HTTP-Cookies
dnf install mpfr
dnf install os-prober
dnf install xemacs-filesystem
dnf install libcanberra-gtk2
dnf install libgcab1
dnf install bcache-tools
dnf install gnome-system-monitor
dnf install libical
dnf install gc
dnf install oxygen-fonts
dnf install kf5-kconfigwidgets
dnf install folks
dnf install gvfs-smb
dnf install libssh2
dnf install qt-x11
dnf install proj
dnf install xerces-c
dnf install fontawesome-fonts
dnf install mactel-boot
dnf install python2-babel
dnf install httpd-filesystem
dnf install libXfixes
dnf install gpg-pubkey-fa7a179a
dnf install libglvnd-opengl
dnf install lklug-fonts
dnf install NetworkManager-wwan
dnf install gnuchess
dnf install quota-nls
dnf install libreport-fedora
dnf install mlocate
dnf install libxml++
dnf install kf5-kio-file-widgets
dnf install openjade
dnf install fontpackages-filesystem
dnf install mokutil
dnf install redhat-lsb-core
dnf install brlapi
dnf install nspr
dnf install desktop-backgrounds-compat
dnf install libffi-devel
dnf install libshout
dnf install python3-pillow
dnf install fedora-repos
dnf install python3-dbus
dnf install libXt
dnf install libXcursor
dnf install mesa-libwayland-egl-devel
dnf install python2
dnf install iwl2030-firmware
dnf install google-noto-sans-mandaic-fonts
dnf install perl-WWW-RobotRules
dnf install garcon
dnf install ghostscript-x11
dnf install libgudev
dnf install libvorbis
dnf install Lmod
dnf install paps-libs
dnf install python3-pygpgme
dnf install perl-Package-Generator
dnf install gnome-session-xsession
dnf install python3-meh
dnf install elfutils-default-yama-scope
dnf install abrt-addon-xorg
dnf install cairo-gobject
dnf install teamd
dnf install dejavu-sans-fonts
dnf install systemd-devel
dnf install hplip-common
dnf install libbasicobjects
dnf install pciutils-libs
dnf install ibus-gtk3
dnf install perl-Encode
dnf install perl-Pod-Checker
dnf install ncurses
dnf install libXau-devel
dnf install taglib
dnf install libevdev
dnf install freexl
dnf install google-noto-sans-meetei-mayek-fonts
dnf install google-crosextra-carlito-fonts
dnf install perl-Math-Complex
dnf install libtool-ltdl
dnf install djvulibre-libs
dnf install gpg-pubkey-b7546f06
dnf install sssd-client
dnf install perl-Scalar-List-Utils
dnf install python3-pycurl
dnf install lrzsz
dnf install x265-libs
dnf install cyrus-sasl-plain
dnf install iso-codes
dnf install rpm-build
dnf install mhash
dnf install mpg123
dnf install libtalloc
dnf install cheese
dnf install lua-libs
dnf install isdn4k-utils-data
dnf install minicom
dnf install json-c
dnf install libffado
dnf install libgnomekbd
dnf install perl-bignum
dnf install ethtool
dnf install device-mapper-multipath-libs
dnf install oxygen-icon-theme
dnf install yum-metadata-parser
dnf install mesa-libOpenCL
dnf install perl-Errno
dnf install orc
dnf install subversion
dnf install gcr
dnf install iptables
dnf install openvpn
dnf install python3-pwquality
dnf install python3-chardet
dnf install boost-type_erasure
dnf install libcgroup
dnf install gnome-icon-theme
dnf install glib2-devel
dnf install libkkc-common
dnf install syslinux
dnf install google-crosextra-caladea-fonts
dnf install perl-HTTP-Date
dnf install lapack
dnf install python3-magic
dnf install hunspell-en
dnf install python2-docutils
dnf install python3-bytesize
dnf install efivar-libs
dnf install redhat-menus
dnf install libreport-plugin-bugzilla
dnf install distribution-gpg-keys
dnf install golang-gopkg-yaml-devel
dnf install im-chooser-common
dnf install cyrus-sasl
dnf install ipset-libs
dnf install python2-pycparser
dnf install libpng-devel
dnf install libglvnd-devel
dnf install redhat-lsb-languages
dnf install libfprint
dnf install nss-pem
dnf install pixman-devel
dnf install libX11-common
dnf install mesa-libEGL
dnf install plymouth-scripts
dnf install libxklavier
dnf install NetworkManager-team
dnf install python2-dnf-plugins-extras-system-upgrade
dnf install pinentry-gtk
dnf install cogl-devel
dnf install python3-pyudev
dnf install libpcap
dnf install gstreamer1-plugins-good
dnf install pinfo
dnf install perl-XML-SAX
dnf install perl-Class-Inspector
dnf install abrt-addon-pstoreoops
dnf install libvdpau
dnf install libzhuyin-data
dnf install libusbx
dnf install python3-systemd
dnf install ed
dnf install dvgrab
dnf install qqwing-libs
dnf install python2-markupsafe
dnf install libcap-devel
dnf install perl-Text-Soundex
dnf install coreutils
dnf install perl-podlators
dnf install libeot
dnf install mobile-broadband-provider-info
dnf install pcre-cpp
dnf install perl-IO-Socket-IP
dnf install libdv
dnf install google-noto-sans-tai-viet-fonts
dnf install skkdic
dnf install NetworkManager-openvpn-gnome
dnf install gawk
dnf install f23-backgrounds-gnome
dnf install vpnc-script
dnf install dhcp-client
dnf install obs-build
dnf install calc
dnf install perl-libs
dnf install libreoffice-gtk3
dnf install xorg-x11-drv-libinput
dnf install libquvi
dnf install libipt
dnf install libxkbcommon-devel
dnf install hesiod
dnf install abrt-desktop
dnf install grilo
dnf install golang-github-syndtr-gocapability-devel
dnf install perl-Encode
dnf install tzdata
dnf install xfce4-screenshooter-plugin
dnf install liboauth
dnf install libini_config
dnf install lohit-assamese-fonts
dnf install gnome-user-share
dnf install libXfont2
dnf install boost-system
dnf install hypervvssd
dnf install uboot-tools
dnf install crda
dnf install python2-cffi
dnf install NetworkManager-iodine
dnf install atmel-firmware
dnf install kf5-kwallet
dnf install indent
dnf install libsemanage-python
dnf install libfontenc
dnf install libsoup-devel
dnf install python3-libs
dnf install samba-common
dnf install cups-pk-helper
dnf install boost-iostreams
dnf install binutils-devel
dnf install psacct
dnf install xml-common
dnf install python3-beautifulsoup4
dnf install lua-term
dnf install libpkgconf
dnf install xfce4-terminal
dnf install setools-python3
dnf install smc-meera-fonts
dnf install perl-XML-SAX-Base
dnf install golang-github-godbus-dbus-devel
dnf install cairo
dnf install abrt-libs
dnf install hypervvssd
dnf install gnutls-dane
dnf install autoconf-archive
dnf install pycairo
dnf install anaconda-widgets
dnf install ctags
dnf install curl
dnf install im-chooser
dnf install librsvg2
dnf install libcap-ng
dnf install PackageKit
dnf install python-enum34
dnf install libXau-devel
dnf install iwl6000-firmware
dnf install gpg-pubkey-f5282ee4
dnf install ebtables
dnf install NetworkManager-iodine-gnome
dnf install libX11-devel
dnf install python3-libcomps
dnf install qt5-qtsvg
dnf install libclc
dnf install iptables-libs
dnf install tumbler
dnf install sqlite-devel
dnf install atkmm
dnf install abrt-retrace-client
dnf install mozjs31
dnf install fuse-common
dnf install perl-MIME-Types
dnf install cryptsetup-libs
dnf install ncurses-devel
dnf install perl-ExtUtils-MM-Utils
dnf install libpciaccess-devel
dnf install xcb-util
dnf install xorg-x11-drv-evdev-devel
dnf install libcgroup
dnf install plymouth
dnf install nautilus-extensions
dnf install kernel-core
dnf install perl-URI
dnf install compiler-rt
dnf install aajohan-comfortaa-fonts
dnf install libXxf86vm-devel
dnf install setserial
dnf install libsamplerate
dnf install python-beaker
dnf install plymouth-core-libs
dnf install vte-profile
dnf install perl-Carp
dnf install gssproxy
dnf install libxkbcommon
dnf install microcode_ctl
dnf install kbd-misc
dnf install guile
dnf install groff-base
dnf install perl-MIME-Types
dnf install pulseaudio-libs
dnf install adwaita-qt-common
dnf install man-db
dnf install xdg-utils
dnf install fros-recordmydesktop
dnf install python3-brlapi
dnf install libcdio-paranoia
dnf install clutter-gtk
dnf install obs-build-mkdrpms
dnf install libdhash
dnf install spax
dnf install libtirpc
dnf install systemd-pam
dnf install gnome-software
dnf install gnome-keyring
dnf install kf5-kguiaddons
dnf install perl-Time-Local
dnf install postgresql-libs
dnf install perl-Pod-LaTeX
dnf install cogl
dnf install python2-pbr
dnf install b43-openfwwf
dnf install libmetalink
dnf install lohit-gujarati-fonts
dnf install perl-ExtUtils-Install
dnf install diffstat
dnf install perl-ExtUtils-Manifest
dnf install dnf-plugins-core
dnf install NetworkManager-strongswan
dnf install libglvnd
dnf install kf5-kxmlgui
dnf install kernel
dnf install hyperv-daemons
dnf install boost-test
dnf install dconf
dnf install fakeroot
dnf install hexedit
dnf install alsa-utils
dnf install yajl
dnf install hawkey
dnf install perl-Module-Metadata
dnf install python3-devel
dnf install libevdev
dnf install NetworkManager-glib
dnf install python3-configobj
dnf install libdrm
dnf install newt
dnf install libverto
dnf install golang-github-bugsnag-bugsnag-go-devel
dnf install libffi-devel
dnf install bash
dnf install stunnel
dnf install fwupd
dnf install python3-aiohttp
dnf install dbus-python
dnf install webkitgtk4-jsc-devel
dnf install perl-Module-Load-Conditional
dnf install parted
dnf install ogdi
dnf install libicu
dnf install gstreamer1-plugins-bad-free
dnf install comps-extras
dnf install mlocate
dnf install libsecret
dnf install libXrender
dnf install abrt
dnf install polkit-qt5
dnf install gpg-pubkey-d38b4796
dnf install slang
dnf install perl-Data-Section
dnf install cdparanoia-libs
dnf install perl-Module-Pluggable
dnf install kpartx
dnf install pptp
dnf install qpdf-libs
dnf install systemd-container
dnf install thunderbird
dnf install five-or-more
dnf install libdc1394
dnf install libblockdev-mpath
dnf install attr
dnf install evolution-data-server
dnf install xapian-core-libs
dnf install perl-Env
dnf install automake
dnf install poppler-qt5
dnf install kbd
dnf install paratype-pt-sans-fonts
dnf install libgsf
dnf install gnome-autoar
dnf install jack-audio-connection-kit
dnf install python2-urllib3
dnf install python3-slip-dbus
dnf install perl-constant
dnf install perl-HTML-Tagset
dnf install python-enum34
dnf install libverto-devel
dnf install libogg-devel
dnf install cmake-data
dnf install libmusicbrainz5
dnf install gpg-pubkey
dnf install libnet
dnf install sssd
dnf install bind-libs
dnf install gstreamer-devel
dnf install audit-libs-python3
dnf install perl-Data-Dump
dnf install gnome-getting-started-docs
dnf install libtdb
dnf install python3-speechd
dnf install libsrtp
dnf install gnome-maps
dnf install perl-version
dnf install faad2-libs
dnf install gnat-srpm-macros
dnf install lohit-tamil-fonts
dnf install hwdata
dnf install libXfont2-devel
dnf install gpgme
dnf install gcr-devel
dnf install gvfs
dnf install libXdmcp
dnf install perl-Text-Tabs+Wrap
dnf install libunistring
dnf install dracut
dnf install libsss_idmap
dnf install boost-random
dnf install dracut-config-rescue
dnf install efivar-devel
dnf install libbabeltrace
dnf install python3-humanize
dnf install syslinux-nonlinux
dnf install python3-distro
dnf install perl-TimeDate
dnf install xcb-util-renderutil
dnf install python3-pwquality
dnf install trousers-lib
dnf install calc-stdrc
dnf install m4
dnf install nss-softokn
dnf install xmlrpc-c
dnf install dvgrab
dnf install kf5-kio-widgets
dnf install subunit
dnf install gpg-pubkey
dnf install libdfu
dnf install libXcomposite-devel
dnf install python2-pip
dnf install libsecret
dnf install libwacom
dnf install oxygen-mono-fonts
dnf install m17n-lib
dnf install at-spi2-core-devel
dnf install gtk-unico-engine
dnf install libertas-usb8388-firmware
dnf install libXfont
dnf install libosinfo
dnf install qt5-qtxmlpatterns
dnf install python3-meh-gui
dnf install NetworkManager-wifi
dnf install phonon-qt5-backend-gstreamer
dnf install clucene-core
dnf install libxml2-devel
dnf install mpg123-libs
dnf install bind-utils
dnf install perl-XML-SAX-Base
dnf install libusb
dnf install libXfixes
dnf install libblockdev
dnf install perl-Digest-HMAC
dnf install libxml2-devel
dnf install python2-libcomps
dnf install hunspell-en
dnf install bsdtar
dnf install mythes-en
dnf install xfce4-panel
dnf install libwmf-lite
dnf install perl-local-lib
dnf install libogg
dnf install webkitgtk4
dnf install lua-expat
dnf install libiscsi
dnf install openssl
dnf install libcanberra
dnf install libass
dnf install procps-ng
dnf install audit
dnf install stix-fonts
dnf install libnetfilter_conntrack
dnf install perl-XML-Parser
dnf install langtable
dnf install abrt-gui-libs
dnf install isl
dnf install redhat-rpm-config
dnf install NetworkManager-vpnc
dnf install rpmfusion-free-appstream-data
dnf install openjpeg-libs
dnf install lohit-telugu-fonts
dnf install libXScrnSaver
dnf install autocorr-en
dnf install elinks
dnf install golang-golangorg-crypto-devel
dnf install wget
dnf install libffi
dnf install open-vm-tools-desktop
dnf install orc
dnf install keyutils
dnf install audit-libs-python
dnf install js-jquery
dnf install perl-HTTP-Negotiate
dnf install rubygems
dnf install NetworkManager-vpnc
dnf install gnome-clocks
dnf install apr
dnf install dbus-x11
dnf install perl-Text-Tabs+Wrap
dnf install libpeas
dnf install perl-Git
dnf install cagibi
dnf install ncurses-devel
dnf install boost-timer
dnf install gnome-documents
dnf install libmnl
dnf install exempi
dnf install glusterfs-libs
dnf install python3-html5lib
dnf install mesa-libGLES
dnf install libv4l
dnf install nmap-ncat
dnf install sane-backends-libs
dnf install gssdp
dnf install gpg-pubkey
dnf install libXi
dnf install perl-Params-Check
dnf install libXfont
dnf install kf5-kinit
dnf install glusterfs-api
dnf install python3-jinja2
dnf install ModemManager
dnf install avahi-gobject
dnf install perl-Pod-Perldoc
dnf install libteam
dnf install samba-client
dnf install fros
dnf install python3-pycparser
dnf install albatross-gtk2-theme
dnf install libXcursor-devel
dnf install perl-HTTP-Cookies
dnf install NetworkManager-strongswan-gnome
dnf install google-noto-sans-lisu-fonts
dnf install libsmbios
dnf install perl-Module-Load
dnf install glx-utils
dnf install llvm-libs
dnf install pulseaudio-libs-glib2
dnf install ghostscript
dnf install crda
dnf install opencc
dnf install akmods
dnf install arch-install-scripts
dnf install libical-devel
dnf install redland
dnf install adcli
dnf install perl-Archive-Tar
dnf install libblockdev-dm
dnf install libpskc
dnf install rpm
dnf install patch
dnf install gtk3
dnf install hplip-libs
dnf install libcdio
dnf install gstreamer1-plugins-bad-freeworld
dnf install vlgothic-fonts
dnf install cpio
dnf install iio-sensor-proxy
dnf install jomolhari-fonts
dnf install pacman
dnf install pcre-utf32
dnf install hesiod
dnf install plymouth-plugin-two-step
dnf install libsndfile
dnf install kf5-filesystem
dnf install qt5-srpm-macros
dnf install python3-ply
dnf install libdmx
dnf install kbd-legacy
dnf install pcsc-lite-libs
dnf install opensp
dnf install hesiod-devel
dnf install cups-filters
dnf install popt
dnf install libassuan
dnf install perl-Term-Cap
dnf install kf5-kdbusaddons
dnf install gtkmm30
dnf install libdb
dnf install libsigc++20
dnf install gdouros-symbola-fonts
dnf install vo-amrwbenc
dnf install xdg-desktop-portal-gtk
dnf install systemd
dnf install libsrtp
dnf install librevenge
dnf install perl-XML-LibXML
dnf install appstream
dnf install python2-idna
dnf install extundelete
dnf install naver-nanum-gothic-fonts
dnf install perl-URI
dnf install psacct
dnf install perl-version
dnf install libXrender-devel
dnf install libbytesize
dnf install e2fsprogs-libs
dnf install libqmi-utils
dnf install gobject-introspection
dnf install perl-Compress-Raw-Zlib
dnf install iputils
dnf install boost-coroutine
dnf install python3-coverage
dnf install file
dnf install gtkspell3
dnf install hunspell-en-US
dnf install xdg-user-dirs-gtk
dnf install perl-CPAN-Meta-Requirements
dnf install aide
dnf install chmlib
dnf install kdecoration
dnf install m17n-lib
dnf install libgtop2
dnf install five-or-more
dnf install shadow-utils
dnf install crontabs
dnf install python2-imagesize
dnf install hesiod-devel
dnf install python-bugzilla
dnf install fipscheck-lib
dnf install libmicrohttpd
dnf install avahi
dnf install ncurses-libs
dnf install sudo
dnf install nmap-ncat
dnf install libXxf86vm-devel
dnf install openblas-srpm-macros
dnf install gnome-icon-theme
dnf install libsmartcols
dnf install libuuid
dnf install libgsf
dnf install google-chrome-unstable
dnf install libxshmfence
dnf install perl-HTTP-Date
dnf install device-mapper-event-libs
dnf install python3-inotify
dnf install xorg-x11-server-source
dnf install bind99-libs
dnf install cronie-anacron
dnf install libXft-devel
dnf install deltarpm
dnf install memtest86+
dnf install perl-Module-Load-Conditional
dnf install compat-readline6
dnf install libbytesize
dnf install libXcomposite
dnf install libalpm
dnf install python-xpyb
dnf install perl-CPAN-Meta
dnf install fuse-libs
dnf install cifs-utils
dnf install lame-libs
dnf install gtk2-devel
dnf install caribou
dnf install clang-libs
dnf install perl-File-Slurp
dnf install libblockdev-part
dnf install libgta
dnf install thunar-archive-plugin
dnf install msr-tools
dnf install libtommath
dnf install libchamplain-gtk
dnf install poppler-utils
dnf install fribidi
dnf install usb_modeswitch
dnf install perl-Archive-Zip
dnf install perl-srpm-macros
dnf install lohit-kannada-fonts
dnf install gtkmm24
dnf install net-snmp-libs
dnf install python2-markupsafe
dnf install rhash
dnf install kf5-kpackage
dnf install libshout
dnf install libcanberra-gtk3
dnf install open-vm-tools
dnf install perl-SGMLSpm
dnf install cryptsetup
dnf install bind-libs-lite
dnf install dbus-libs
dnf install perl-Exporter
dnf install kf5-attica
dnf install perl-generators
dnf install http-parser
dnf install libgta
dnf install libattr
dnf install swell-foop
dnf install xfce4-pulseaudio-plugin
dnf install twolame-libs
dnf install gstreamer-tools
dnf install gnome-color-manager
dnf install perl-Digest-SHA
dnf install qemu-common
dnf install nspr-devel
dnf install libacl-devel
dnf install b43-fwcutter
dnf install krb5-libs
dnf install cpulimit
dnf install vala
dnf install ltrace
dnf install libxfce4ui
dnf install libpwquality
dnf install gvfs-mtp
dnf install dleyna-core
dnf install kernel-devel
dnf install python3-markupsafe
dnf install bluez-obexd
dnf install tcl
dnf install grep
dnf install nss-util-devel
dnf install python3-lxml
dnf install libunwind
dnf install python3-markupsafe
dnf install perl-Sub-Install
dnf install ghostscript-fonts
dnf install syslinux-extlinux-nonlinux
dnf install rubygem-psych
dnf install cairo-gobject
dnf install httpd
dnf install python2-pyOpenSSL
dnf install passwd
dnf install fcoe-utils
dnf install udisks2
dnf install mesa-libxatracker
dnf install libimobiledevice
dnf install libjpeg-turbo
dnf install desktop-backgrounds-gnome
dnf install cogl
dnf install qt5-qtbase
dnf install libgcrypt-devel
dnf install libssh
dnf install fedora-release-notes
dnf install python3-cups
dnf install iwl2000-firmware
dnf install gperftools-libs
dnf install libdatrie
dnf install lua
dnf install perl-Locale-Maketext
dnf install NetworkManager-config-connectivity-fedora
dnf install libwsman1
dnf install kmod-libs
dnf install pacman-filesystem
dnf install perl-IO-HTML
dnf install lua-socket
dnf install gutenprint-libs
dnf install python-rpm-macros
dnf install libverto-devel
dnf install xkeyboard-config
dnf install libXft
dnf install libnfsidmap
dnf install lksctp-tools
dnf install perl-Devel-Size
dnf install xorg-x11-drv-synaptics-devel
dnf install perl-Time-HiRes
dnf install ibus-gtk2
dnf install f24-backgrounds-gnome
dnf install adobe-source-han-sans-cn-fonts
dnf install libunicap
dnf install libtiff
dnf install perl-Module-Runtime
dnf install sgml-common
dnf install perl-HTTP-Message
dnf install perl-threads-shared
dnf install python-mako
dnf install python3-librepo
dnf install kf5-kcodecs
dnf install fros-recordmydesktop
dnf install openjpeg-libs
dnf install libnl3-cli
dnf install mesa-libGLU
dnf install perl-Email-Date-Format
dnf install perl-Data-Dumper
dnf install kmod-VirtualBox
dnf install xorg-x11-xauth
dnf install rpm-devel
dnf install firewall-config
dnf install libkml
dnf install perl-parent
dnf install valgrind
dnf install docbook-utils
dnf install golang-github-coreos-go-semver-devel
dnf install python3-rpm-macros
dnf install gnome-contacts
dnf install ostree
dnf install baobab
dnf install perl-Unicode-Normalize
dnf install iscsi-initiator-utils-iscsiuio
dnf install pocl
dnf install xorg-x11-drv-vesa
dnf install clutter-gst3
dnf install libuuid-devel
dnf install json-glib
dnf install NetworkManager-openconnect
dnf install anaconda-user-help
dnf install boost-atomic
dnf install dleyna-core
dnf install sqlite
dnf install libwayland-cursor
dnf install libao
dnf install grubby
dnf install grub2-tools
dnf install python3-gobject-base
dnf install cups-client
dnf install libdatrie
dnf install lua-filesystem
dnf install libiptcdata
dnf install xorg-x11-server-common
dnf install perl-Crypt-SSLeay
dnf install gnome-tetravex
dnf install pam
dnf install python-libxml2
dnf install bind99-license
dnf install libpsl
dnf install perl-Mozilla-CA
dnf install SDL_image
dnf install nss-softokn-devel
dnf install kde-settings
dnf install libXi-devel
dnf install gmp-devel
dnf install aajohan-comfortaa-fonts
dnf install xorg-x11-server-devel
dnf install libfontenc-devel
dnf install libsss_sudo
dnf install gnuchess
dnf install libSM
dnf install ncurses-libs
dnf install cvs
dnf install golang-golangorg-text-devel
dnf install libxcb
dnf install gnome-klotski
dnf install libselinux-devel
dnf install qt5-qtx11extras
dnf install bzip2-devel
dnf install glibc-headers
dnf install libXxf86misc
dnf install perl-Encode-Locale
dnf install gmime
dnf install minizip
dnf install gavl
dnf install docker-latest-devel
dnf install python2-pysocks
dnf install perl-ExtUtils-CBuilder
dnf install gutenprint
dnf install gnome-taquin
dnf install dmraid
dnf install hyphen
dnf install lockdev
dnf install libblockdev-fs
dnf install libstdc++
dnf install perl-Algorithm-Diff
dnf install less
dnf install python3-pyparted
dnf install exiv2-libs
dnf install gstreamer1-plugins-ugly
dnf install sil-padauk-fonts
dnf install libkml
dnf install tabish-eeyek-fonts
dnf install mesa-libGLU
dnf install firewalld
dnf install python-beaker
dnf install geos
dnf install gettext-common-devel
dnf install python-qt5-rpm-macros
dnf install perl-JSON-PP
dnf install gsm
dnf install kf5-kcoreaddons
dnf install pciutils-devel
dnf install msr-tools
dnf install hplip-common
dnf install libfdt
dnf install libreswan
dnf install gcc-c++
dnf install openjade
dnf install perl-LWP-MediaTypes
dnf install kf5-kservice
dnf install perl-File-Temp
dnf install libdvdnav
dnf install libconfig
dnf install perl-MIME-Base64
dnf install libfdisk
dnf install libpeas-gtk
dnf install dbus
dnf install libhbaapi
dnf install perl-Pod-Simple
dnf install libvorbis-devel
dnf install hunspell-en-GB
dnf install gmime
dnf install clutter-gtk
dnf install thunar-volman
dnf install libpath_utils
dnf install file-roller-nautilus
dnf install dbusmenu-qt
dnf install hypervkvpd
dnf install boost-chrono
dnf install libtheora
dnf install libselinux
dnf install NetworkManager-ssh
dnf install container-selinux
dnf install python3-gpg
dnf install lockdev-devel
dnf install kf5-kjs
dnf install evince-nautilus
dnf install python-chardet
dnf install bluez-libs
dnf install libiec61883
dnf install xmlsec1
dnf install python3-lxml
dnf install freetype-devel
dnf install pkgconf
dnf install mokutil
dnf install cronie
dnf install thai-scalable-waree-fonts
dnf install xfwm4
dnf install libXrender
dnf install rubygem-io-console
dnf install python3-nose
dnf install gnutls-utils
dnf install ncurses-base
dnf install abrt-addon-coredump-helper
dnf install dmidecode
dnf install GeoIP
dnf install b43-openfwwf
dnf install perl-libintl-perl
dnf install PyYAML
dnf install google-noto-emoji-fonts
dnf install gtk2
dnf install libnm-gtk
dnf install python2-appdirs
dnf install iwl5150-firmware
dnf install nss-mdns
dnf install perl-HTTP-Message
dnf install gtk-update-icon-cache
dnf install gnome-robots
dnf install qt5-qtscript
dnf install mallard-rng
dnf install perl-Compress-Bzip2
dnf install gnome-desktop3
dnf install atkmm
dnf install f26-backgrounds-base
dnf install perl-Software-License
dnf install gettext-libs
dnf install python3-augeas
dnf install ebtables
dnf install dbus-devel
dnf install python3-libxml2
dnf install cyrus-sasl-devel
dnf install words
dnf install gstreamer1-plugins-bad-free-gtk
dnf install audit-libs
dnf install nautilus-sendto
dnf install perl-CGI
dnf install linux-atm-libs
dnf install naver-nanum-gothic-fonts
dnf install gnome-online-accounts-devel
dnf install libXdamage-devel
dnf install lohit-telugu-fonts
dnf install perl-Encode-Locale
dnf install ghostscript
dnf install pycryptopp
dnf install libxml2
dnf install javapackages-tools
dnf install sssd-ad
dnf install python-gssapi
dnf install libhbalinux
dnf install cyrus-sasl-lib
dnf install libpipeline
dnf install libplist
dnf install opencc
dnf install mozilla-filesystem
dnf install libnfnetlink
dnf install p11-kit
dnf install less
dnf install perl-Term-ANSIColor
dnf install libsolv
dnf install libtool
dnf install fakeroot-libs
dnf install breeze-icon-theme
dnf install device-mapper-event
dnf install libmimic
dnf install google-noto-fonts-common
dnf install mtdev
dnf install fpc-srpm-macros
dnf install gstreamer
dnf install kf5-kglobalaccel-libs
dnf install gnome-nibbles
dnf install perl-File-ShareDir
dnf install xorg-x11-drv-evdev
dnf install perl-Data-Dumper
dnf install findutils
dnf install exo
dnf install qemu-block-dmg
dnf install libstemmer
dnf install libmwaw
dnf install libverto
dnf install glib-networking
dnf install python3-ntplib
dnf install gvfs-gphoto2
dnf install jack-audio-connection-kit
dnf install libvpx
dnf install kf5-threadweaver
dnf install iproute-tc
dnf install quadrapassel
dnf install python3-jsonschema
dnf install binutils
dnf install kernel-core
dnf install boost
dnf install wayland-protocols-devel
dnf install perl-Params-Util
dnf install python2-funcsigs
dnf install kwin-common
dnf install ghostscript-core
dnf install rubygem-openssl
dnf install python-gssapi
dnf install nss-tools
dnf install alsa-utils
dnf install libkkc
dnf install f24-backgrounds-base
dnf install libXinerama-devel
dnf install xz-libs
dnf install fprintd-pam
dnf install libcap
dnf install sane-backends-drivers-scanners
dnf install perl-File-ShareDir
dnf install liberation-mono-fonts
dnf install net-tools
dnf install zip
dnf install hicolor-icon-theme
dnf install libipa_hbac
dnf install qt5-qtlocation
dnf install iwl135-firmware
dnf install lua-lpeg
dnf install qt5-qtmultimedia
dnf install imsettings-libs
dnf install libcdio
dnf install libcom_err-devel
dnf install augeas-libs
dnf install python2-cffi
dnf install libgxps
dnf install libtasn1
dnf install python3-pyOpenSSL
dnf install perl-Class-Inspector
dnf install perl-File-Which
dnf install foomatic-db
dnf install OpenEXR-libs
dnf install libgusb
dnf install isdn4k-utils-data
dnf install virglrenderer
dnf install ibus-libs
dnf install perl-Devel-Size
dnf install colord-libs
dnf install openCOLLADA
dnf install uriparser
dnf install libquvi
dnf install fakeroot
dnf install libXfont2
dnf install google-noto-sans-lisu-fonts
dnf install perl-generators
dnf install mailx
dnf install jbigkit-libs
dnf install f23-backgrounds-base
dnf install libtiff
dnf install fedora-logos-httpd
dnf install perl-XML-SAX
dnf install pcmciautils
dnf install kf5-kauth
dnf install sssd-krb5-common
dnf install gdk-pixbuf2
dnf install iptables
dnf install bzip2-libs
dnf install pcre-devel
dnf install mtdev
dnf install systemd-libs
dnf install hitori
dnf install libestr
dnf install libtool-ltdl
dnf install gnome-terminal
dnf install libquvi-scripts
dnf install gnome-user-docs
dnf install libtheora
dnf install perl-Socket
dnf install sed
dnf install libfbclient2
dnf install mjpegtools-libs
dnf install python3-pyparted
dnf install libedit
dnf install GeoIP-GeoLite-data
dnf install libiec61883
dnf install libXau
dnf install perl-Test-Harness
dnf install eog
dnf install openal-soft
dnf install perl-libnet
dnf install at
dnf install osinfo-db-tools
dnf install perl-File-Path
dnf install greybird-xfwm4-theme
dnf install libpcap
dnf install gspell
dnf install golang-github-jonboulle-clockwork-devel
dnf install libbsd
dnf install gvfs-client
dnf install libdc1394
dnf install qemu-block-nfs
dnf install libXrandr-devel
dnf install boost-date-time
dnf install libyaml
dnf install libuser-devel
dnf install system-python-libs
dnf install gvfs-fuse
dnf install brltty
dnf install libwayland-server
dnf install hyperv-daemons
dnf install kf5-libkexiv2
dnf install netpbm
dnf install boost-signals
dnf install python-gobject
dnf install libmcpp
dnf install gnome-klotski
dnf install at-spi2-atk
dnf install mozjs38
dnf install NetworkManager
dnf install mpg123-plugins-jack
dnf install chkconfig
dnf install fontawesome-fonts-web
dnf install mhash
dnf install check
dnf install glusterfs-client-xlators
dnf install libatomic_ops
dnf install qt-common
dnf install google-noto-fonts-common
dnf install numactl-libs
dnf install python-bugzilla-cli
dnf install dracut-config-rescue
dnf install groff-base
dnf install poppler-data
dnf install libXfixes-devel
dnf install libreport-plugin-logger
dnf install geoclue2
dnf install liblogging-stdlog
dnf install libedit
dnf install libusbmuxd
dnf install xmlrpc-c-client
dnf install dbus-glib
dnf install libaio
dnf install perl-Math-BigInt
dnf install syslinux-extlinux
dnf install gtk2
dnf install fontconfig-devel
dnf install libsoup
dnf install redhat-lsb
dnf install liboauth-devel
dnf install docbook-utils
dnf install fedora-release
dnf install libXres
dnf install gsettings-desktop-schemas-devel
dnf install SDL
dnf install openssh-askpass
dnf install openjpeg2
dnf install rubygem-did_you_mean
dnf install expat
dnf install python2-six
dnf install qt5-qtenginio
dnf install python3-humanize
dnf install libibverbs
dnf install cairo-devel
dnf install iwl100-firmware
dnf install libmbim
dnf install fwupdate-libs
dnf install python3-brlapi
dnf install net-tools
dnf install docker-rhel-push-plugin
dnf install avahi-glib
dnf install python3-six
dnf install perl-Pod-LaTeX
dnf install python3-dbus
dnf install libhangul
dnf install libserf
dnf install libmtp
dnf install keyutils-libs
dnf install libidn2
dnf install evince
dnf install abrt-plugin-bodhi
dnf install python3-psutil
dnf install neon
dnf install perl-inc-latest
dnf install openssl-devel
dnf install pinentry
dnf install abattis-cantarell-fonts
dnf install caribou-gtk2-module
dnf install cogl-devel
dnf install libotf
dnf install adwaita-cursor-theme
dnf install rpm-libs
dnf install plymouth-graphics-libs
dnf install python3-beautifulsoup4
dnf install libcollection
dnf install perl-Module-Pluggable
dnf install libcurl-devel
dnf install python-backports-ssl_match_hostname
dnf install python2-requests
dnf install perl-Pod-Simple
dnf install lua-json
dnf install cvs
dnf install procps-ng
dnf install pixman
dnf install libodfgen
dnf install mtr
dnf install apr-util
dnf install nghttp2
dnf install gdb
dnf install google-noto-sans-tagalog-fonts
dnf install perl-inc-latest
dnf install libao
dnf install libbasicobjects
dnf install pixman-devel
dnf install calc-libs
dnf install kmodtool
dnf install libreoffice-ure-common
dnf install gnu-free-sans-fonts
dnf install python2-babel
dnf install freetype
dnf install libsss_nss_idmap
dnf install golang-github-stretchr-objx-devel
dnf install libcrypt-nss
dnf install gcc
dnf install perl-File-Path
dnf install satyr
dnf install gutenprint
dnf install imvirt
dnf install golang-github-pmezard-go-difflib-devel
dnf install parted
dnf install libdv
dnf install libxml++
dnf install glibc-all-langpacks
dnf install crontabs
dnf install marisa
dnf install keyutils-libs-devel
dnf install libgnome-games-support
dnf install xfwm4-theme-nodoka
dnf install fedora-bookmarks
dnf install khmeros-base-fonts
dnf install xorg-x11-drv-nouveau
dnf install bridge-utils
dnf install teamd
dnf install liblouis
dnf install systemd-bootchart
dnf install python3-decorator
dnf install cracklib-dicts
dnf install webkitgtk3
dnf install gnome-abrt
dnf install logrotate
dnf install xcb-util-wm
dnf install python-backports
dnf install iptstate
dnf install libwacom-data
dnf install NetworkManager-iodine-gnome
dnf install libhif
dnf install liborcus
dnf install google-noto-sans-meetei-mayek-fonts
dnf install python3-requests-file
dnf install hexedit
dnf install NetworkManager-openconnect-gnome
dnf install libhif
dnf install dejavu-sans-mono-fonts
dnf install xfconf
dnf install soundtouch
dnf install gtk-xfce-engine
dnf install isomd5sum
dnf install plymouth-plugin-two-step
dnf install traceroute
dnf install xorg-x11-font-utils
dnf install google-crosextra-caladea-fonts
dnf install freexl
dnf install sil-mingzat-fonts
dnf install xorg-x11-fonts-ISO8859
dnf install perl-Module-Runtime
dnf install libXxf86dga
dnf install lshw-B.02.18
dnf install gcr
dnf install libieee1284
dnf install python2-blockdev
dnf install lm_sensors-libs
dnf install perl-Socket
dnf install libsepol-devel
dnf install ocl-icd
dnf install kf5-kcrash
dnf install ostree-libs
dnf install julietaula-montserrat-fonts
dnf install libdb-devel
dnf install libverto-tevent
dnf install jbigkit-libs
dnf install python3-wrapt
dnf install lightsoff
dnf install libacl
dnf install clutter
dnf install gom
dnf install opencore-amr
dnf install automake
dnf install createrepo_c-libs
dnf install kpartx
dnf install gnome-characters
dnf install ibus-typing-booster
dnf install boost-thread
dnf install liboauth
dnf install qemu-block-iscsi
dnf install perl-macros
dnf install libwayland-client
dnf install python3-configobj
dnf install nss-util
dnf install libgda-devel
dnf install mesa-libGL-devel
dnf install libtasn1
dnf install boost-log
dnf install cracklib
dnf install exo
dnf install oci-systemd-hook
dnf install kf5-solid
dnf install gd
dnf install gedit
dnf install python3
dnf install libpskc
dnf install libkkc-data
dnf install dmraid-events
dnf install libinput-devel
dnf install libavc1394
dnf install GConf2
dnf install avahi
dnf install hwloc-libs
dnf install glusterfs
dnf install kbd
dnf install lasi
dnf install libappstream-glib
dnf install gnome-mahjongg
dnf install libcomps
dnf install gmp
dnf install cronie-anacron
dnf install libdaemon
dnf install python3-bugzilla
dnf install libcurl
dnf install golang-github-bugsnag-panicwrap-devel
dnf install libXi-devel
dnf install libreport-plugin-ureport
dnf install Thunar
dnf install libXtst
dnf install libsilc
dnf install npth
dnf install lockdev
dnf install mbedtls
dnf install libmng
dnf install geoclue2-libs
dnf install xen-licenses
dnf install ntp
dnf install device-mapper
dnf install perl-Unicode-EastAsianWidth
dnf install libusbmuxd
dnf install glib-networking
dnf install xscreensaver-base
dnf install redhat-lsb-printing
dnf install ncurses-base
dnf install libsigc++20
dnf install phonon-qt5-backend-gstreamer
dnf install mesa-libGL
dnf install libXau
dnf install libXv
dnf install plymouth-plugin-label
dnf install libxfce4util
dnf install libxkbcommon-x11
dnf install iwl5000-firmware
dnf install liboauth-devel
dnf install pycryptopp
dnf install fpaste
dnf install python3-dnf-plugins-extras-system-upgrade
dnf install qt5-qtconnectivity
dnf install cairomm
dnf install lcms2
dnf install plasma-workspace-common
dnf install argyllcms
dnf install cpio
dnf install geocode-glib
dnf install perl-Pod-Plainer
dnf install google-roboto-slab-fonts
dnf install kmod
dnf install python2-setuptools
dnf install keyrings-filesystem
dnf install abrt-addon-vmcore
dnf install bluebird-gtk2-theme
dnf install libXxf86vm
dnf install gettext
dnf install libgda
dnf install perl-IPC-System-Simple
dnf install python-IPy-python3
dnf install flex
dnf install xorg-x11-proto-devel
dnf install xfsprogs
dnf install xorg-x11-xbitmaps
dnf install libXaw
dnf install kbd-misc
dnf install libblockdev-mdraid
dnf install perl-CPAN-Meta-YAML
dnf install fftw-libs-double
dnf install python-backports
dnf install python3-requests
dnf install perl-B-Lint
dnf install python3-pyxdg
dnf install pciutils
dnf install libldb
dnf install pcre
dnf install iw
dnf install gjs
dnf install libcmis
dnf install python3-yarl
dnf install cscope
dnf install perl-Digest-SHA
dnf install ibus-hangul
dnf install telepathy-filesystem
dnf install cryptopp
dnf install libstdc++-devel
dnf install libpciaccess-devel
dnf install fakeroot-libs
dnf install libgrss
dnf install perl-IO-HTML
dnf install librepo
dnf install gnu-free-mono-fonts
dnf install python2-pyasn1-modules
dnf install libass
dnf install python3-urllib3
dnf install kf5-kconfig-gui
dnf install obs-build-mkbaselibs
dnf install bzip2-libs
dnf install calc-libs
dnf install perl-ExtUtils-MM-Utils
dnf install perl-Crypt-SSLeay
dnf install libgcrypt
dnf install xcb-util-image
dnf install python3-raven
dnf install cracklib
dnf install cmake
dnf install kf5-kitemviews
dnf install VirtualBox-server
dnf install libverto-tevent
dnf install iso-codes
dnf install dnf-yum
dnf install perl-CGI
dnf install ipw2100-firmware
dnf install xfdesktop
dnf install python-tempita
dnf install perl-libintl-perl
dnf install enca
dnf install adcli
dnf install bluebird-gtk3-theme
dnf install jack-audio-connection-kit-example-clients
dnf install gtk-unico-engine
dnf install tali
dnf install xorg-x11-util-macros
dnf install espeak
dnf install ModemManager
dnf install libpsl
dnf install jwhois
dnf install albatross-gtk3-theme
dnf install python2-paste
dnf install thunar-media-tags-plugin
dnf install xorg-x11-server-utils
dnf install google-noto-sans-tai-viet-fonts
dnf install patchutils
dnf install ibus-libzhuyin
dnf install usbutils
dnf install liberation-serif-fonts
dnf install schroedinger
dnf install perl-Sys-Syslog
dnf install lapack
dnf install tree
dnf install adobe-source-han-sans-tw-fonts
dnf install isdn4k-utils
dnf install sil-nuosu-fonts
dnf install albatross-gtk2-theme
dnf install pkcs11-helper
dnf install media-player-info
dnf install mcpp
dnf install liblockfile
dnf install aide
dnf install libxfce4ui
dnf install f23-backgrounds-base
dnf install libcap-ng
dnf install kf5-sonnet-ui
dnf install autogen-libopts
dnf install vim-minimal
dnf install seavgabios-bin
dnf install m17n-db
dnf install librsvg2
dnf install hostname
dnf install publicsuffix-list-dafsa
dnf install gpg-pubkey
dnf install gupnp-av
dnf install gnome-backgrounds
dnf install kernel-devel
dnf install lohit-bengali-fonts
dnf install libmodman
dnf install gnome-keyring-pam
dnf install libexif
dnf install perl-MIME-Base64
dnf install libXcomposite-devel
dnf install libss
dnf install qemu-block-ssh
dnf install mesa-libwayland-egl
dnf install libwebp
dnf install orca
dnf install kf5-kpty
dnf install boost-fiber
dnf install acl
dnf install gvfs-afp
dnf install giflib
dnf install plymouth-graphics-libs
dnf install libmbim
dnf install blas
dnf install libmediaart
dnf install libnotify-devel
dnf install lua-lpeg
dnf install kscreenlocker
dnf install python3-gobject
dnf install lua-posix
dnf install dejavu-serif-fonts
dnf install libthai
dnf install perl-Error
dnf install four-in-a-row
dnf install isomd5sum
dnf install info
dnf install ruby-irb
dnf install grub2
dnf install libspectre
dnf install libsmbclient
dnf install a52dec
dnf install libreport
dnf install NetworkManager-libreswan
dnf install kf5-kparts
dnf install gdisk
dnf install gnome-themes-standard
dnf install trousers
dnf install kexec-tools
dnf install libXxf86vm
dnf install libgudev
dnf install f24-backgrounds-gnome
dnf install docbook-style-dsssl
dnf install gnome-themes
dnf install lmdb-libs
dnf install doxygen
dnf install wayland-devel
dnf install python3-bytesize
dnf install xorg-x11-server-Xorg
dnf install e2fsprogs
dnf install qt5-qtbase-gui
dnf install gobject-introspection-devel
dnf install pangomm
dnf install glibmm24
dnf install perl-TimeDate
dnf install openldap
dnf install raptor2
dnf install golang-golangorg-crypto-devel
dnf install cyrus-sasl-gssapi
dnf install iwl3160-firmware
dnf install archlinux-keyring
dnf install PackageKit-command-not-found
dnf install qt5-qttools-libs-designer
dnf install libsepol
dnf install graphite2
dnf install paps-libs
dnf install linux-atm-libs
dnf install ModemManager-glib
dnf install passwdqc
dnf install perl-Params-Check
dnf install glibc-devel
dnf install avahi-autoipd
dnf install python3-cffi
dnf install python2-pygments
dnf install cfitsio
dnf install abrt-addon-kerneloops
dnf install libgdither
dnf install libXinerama
dnf install foomatic-db-ppds
dnf install device-mapper-event
dnf install perl-Algorithm-Diff
dnf install exiv2-libs
dnf install libmfx
dnf install libdvdread
dnf install cairo-gobject-devel
dnf install libXvMC
dnf install libhbalinux
dnf install avahi-gobject
dnf install java
dnf install perl-Archive-Zip
dnf install libblockdev-swap
dnf install mozjs17
dnf install perl-Pod-Escapes
dnf install ibus-setup
dnf install python2-libcomps
dnf install mobile-broadband-provider-info
dnf install espeak
dnf install oxygen-fonts-common
dnf install google-noto-sans-mandaic-fonts
dnf install perl-ExtUtils-Install
dnf install dnf
dnf install libreport-gtk
dnf install perl-Locale-Codes
dnf install yelp-tools
dnf install perl-TermReadKey
dnf install opencl-filesystem
dnf install gtksourceview3
dnf install cpulimit
dnf install abattis-cantarell-fonts
dnf install foomatic-db-filesystem
dnf install kf5-kwindowsystem
dnf install libepoxy-devel
dnf install pango-devel
dnf install perl-Module-Build
dnf install libcom_err
dnf install libreoffice-x11
dnf install libxkbcommon
dnf install VirtualBox-kmodsrc
dnf install perl-Module-Find
dnf install pangomm
dnf install device-mapper-libs
dnf install lz4-libs
dnf install itstool
dnf install libgpg-error-devel
dnf install perl-bignum
dnf install mozilla-filesystem
dnf install libyaml
dnf install perl-parent
dnf install mesa-dri-drivers
dnf install xfce4-datetime-plugin
dnf install perl-WWW-RobotRules
dnf install dotconf
dnf install xorg-x11-drv-qxl
dnf install librdmacm
dnf install arpack
dnf install unbound-libs
dnf install nss-mdns
dnf install python2-kitchen
dnf install compat-openssl10
dnf install python2-decorator
dnf install python2-sphinx
dnf install python-backports-ssl_match_hostname
dnf install quota
dnf install qt3
dnf install elfutils-libs
dnf install upower
dnf install zd1211-firmware
dnf install totem-pl-parser
dnf install telnet
dnf install libmetalink
dnf install shared-mime-info
dnf install perl-Locale-Maketext
dnf install libglade2
dnf install libsysfs
dnf install mpage
dnf install libgrss
dnf install libmspack
dnf install libteam
dnf install kernel-modules-extra
dnf install gnome-video-effects
dnf install lightdm-gobject
dnf install libXv
dnf install libunwind
dnf install protobuf-compiler
dnf install devhelp
dnf install oxygen-fonts
dnf install libXi
dnf install authconfig
dnf install libraw1394
dnf install xorg-x11-drv-libinput-devel
dnf install kf5-kio-ntlm
dnf install perl-HTTP-Tiny
dnf install perl-Net-SSLeay
dnf install gnome-font-viewer
dnf install python3-meh
dnf install python3-jinja2
dnf install gnome-chess
dnf install lohit-gurmukhi-fonts
dnf install deltarpm
dnf install pcsc-lite-libs
dnf install greybird-xfce4-notifyd-theme
dnf install socat
dnf install git-core-doc
dnf install libbluray
dnf install libICE
dnf install abrt-cli
dnf install glib2
dnf install perl-CPAN-Meta-Requirements
dnf install openjpeg2
dnf install boost-context
dnf install kf5-ktextwidgets
dnf install mcpp
dnf install kernel-modules-extra
dnf install brlapi
dnf install logrotate
dnf install newt-python3
dnf install libgee
dnf install docbook-style-xsl
dnf install boost-serialization
dnf install gnu-efi-devel
dnf install libgltf
dnf install NetworkManager-libnm
dnf install jansson
dnf install mpg123-plugins-pulseaudio
dnf install gavl
dnf install python3-async-timeout
dnf install liberation-sans-fonts
dnf install libxkbcommon-devel
dnf install jack-audio-connection-kit-example-clients
dnf install dbus-glib
dnf install kernel-headers
dnf install libXdamage
dnf install mesa-libgbm-devel
dnf install grubby
dnf install perl-Term-ANSIColor
dnf install kf5-kio-widgets-libs
dnf install gnupg2
dnf install sssd-nfs-idmap
dnf install libreport-cli
dnf install libical-devel
dnf install ncurses-c++-libs
dnf install efibootmgr
dnf install kf5-knewstuff
dnf install kernel-devel
dnf install NetworkManager-bluetooth
dnf install perl-Math-BigRat
dnf install flac-libs
dnf install libxfce4util
dnf install libpeas-loader-python3
dnf install json-glib-devel
dnf install openldap
dnf install iwl7260-firmware
dnf install marisa
dnf install python2-libs
dnf install gdk-pixbuf2-devel
dnf install polkit-libs
dnf install openssh-clients
dnf install plymouth
dnf install rubygem-bigdecimal
dnf install imsettings-libs
dnf install libXaw
dnf install libacl
dnf install libgeotiff
dnf install libselinux-utils
dnf install perl-HTTP-Negotiate
dnf install perl-Term-Cap
dnf install perl-Module-Metadata
dnf install python-srpm-macros
dnf install openconnect
dnf install ruby
dnf install libXext
dnf install abrt-dbus
dnf install graphite2-devel
dnf install perl-ExtUtils-Command
dnf install libidn
dnf install perl-devel
dnf install celt051
dnf install python3-setuptools
dnf install NetworkManager-pptp
dnf install iptstate
dnf install khmeros-fonts-common
dnf install gnome-menus
dnf install libblockdev-btrfs
dnf install perl-IPC-System-Simple
dnf install media-player-info
dnf install rpm-plugin-selinux
dnf install p11-kit-trust
dnf install gdisk
dnf install gtk3-devel
dnf install perl-Getopt-Long
dnf install lzo
dnf install perl-File-CheckTree
dnf install opus
dnf install dnf-conf
dnf install time
dnf install devhelp-libs
dnf install google-noto-sans-tai-tham-fonts
dnf install perl-Digest-HMAC
dnf install libcollection
dnf install perl-Pod-Html
dnf install pcre-utf16
dnf install calc
dnf install glibc-common
dnf install protobuf
dnf install geos
dnf install perl-Text-Unidecode
dnf install dracut-network
dnf install fontpackages-filesystem
dnf install libcomps
dnf install cpp
dnf install kf5-kjobwidgets
dnf install dejavu-fonts-common
dnf install python-httplib2
dnf install sssd-krb5
dnf install perl-Scalar-List-Utils
dnf install libwnck3
dnf install graphite2-devel
dnf install flatpak
dnf install lcms2
dnf install gdbm-devel
dnf install libfprint
dnf install perl-Try-Tiny
dnf install perl-Fedora-VSP
dnf install lzo
dnf install libcue
dnf install libnotify-devel
dnf install grilo-plugins
dnf install rubypick
dnf install gnome-devel-docs
dnf install perl-NTLM
dnf install python2-sphinx-theme-alabaster
dnf install dbusmenu-qt5
dnf install mpg123-plugins-pulseaudio
dnf install gfbgraph
dnf install rng-tools
dnf install SuperLU
dnf install perl-CPAN
dnf install python-ipaddr
dnf install libmicrohttpd
dnf install graphviz
dnf install xdg-user-dirs
dnf install python-IPy-python3
dnf install python3-louis
dnf install polkit-qt5
dnf install bash-completion
dnf install python3-ordered-set
dnf install xorg-x11-xinit
dnf install mcelog
dnf install NetworkManager-libreswan-gnome
dnf install pycairo
dnf install source-highlight
dnf install yelp-libs
dnf install perl-File-Listing
dnf install four-in-a-row
dnf install bison
dnf install libxkbcommon-x11
dnf install hostname
dnf install wavpack
dnf install perl-Try-Tiny
dnf install intltool
dnf install golang-github-godbus-dbus-devel
dnf install sshpass
dnf install paktype-naskh-basic-fonts
dnf install paps
dnf install dhcp-libs
dnf install rdist
dnf install python3-firewall
dnf install oci-register-machine
dnf install libXxf86misc
dnf install blas
dnf install byacc
dnf install tcp_wrappers
dnf install libnfs
dnf install libmwaw
dnf install rpmdevtools
dnf install ncurses-c++-libs
dnf install oxygen-sans-fonts
dnf install drpm
dnf install perl-Text-ParseWords
dnf install volume_key-libs
dnf install gnome-weather
dnf install lvm2-libs
dnf install libxslt
dnf install libdca
dnf install autoconf
dnf install libtomcrypt
dnf install perl-constant
dnf install python-urlgrabber
dnf install gnome-mines
dnf install sushi
dnf install golang-bitbucket-kardianos-osext-devel
dnf install xcb-util-cursor
dnf install perl-Time-HiRes
dnf install pulseaudio-utils
dnf install qemu-block-curl
dnf install python3-cffi
dnf install libgnome-games-support
dnf install policycoreutils-python
dnf install perl
dnf install clutter-gtk-devel
dnf install bluez
dnf install fontconfig
dnf install gpm-libs
dnf install libsoup
dnf install qemu-guest-agent
dnf install alsa-lib
dnf install perl-LWP-MediaTypes
dnf install perl-IO-Socket-SSL
dnf install iputils
dnf install libdaemon
dnf install python2-jinja2
dnf install libgusb
dnf install imsettings-gsettings
dnf install spice-server
dnf install libwbclient
dnf install boost-math
dnf install libhbaapi
dnf install nss
dnf install gupnp-av
dnf install adobe-source-han-sans-tw-fonts
dnf install flac-libs
dnf install python3-packaging
dnf install iagno
dnf install libalpm
dnf install libnma
dnf install libXext
dnf install cups-filesystem
dnf install nss-softokn-freebl
dnf install perl-Error
dnf install glib2-doc
dnf install kf5-kio-core-libs
dnf install libgcab1
dnf install libwnck
dnf install oci-register-machine
dnf install hypervkvpd
dnf install popt-devel
dnf install python3-html5lib
dnf install dkms
dnf install kernel-modules-extra
dnf install libreport-anaconda
dnf install python2-packaging
dnf install kf5-kcmutils
dnf install NetworkManager-strongswan
dnf install m17n-db
dnf install khmeros-fonts-common
dnf install oxygen-sans-fonts
dnf install texinfo
dnf install brltty
dnf install opusfile
dnf install redhat-lsb-cxx
dnf install gtk-doc
dnf install shim
dnf install libtar
dnf install libdap
dnf install libattr-devel
dnf install python3-hawkey
dnf install iwl6000g2a-firmware
dnf install qt5-qtsensors
dnf install libqmi
dnf install zenity
dnf install perl-Sub-Install
dnf install mpg123
dnf install oxygen-sound-theme
dnf install diffutils
dnf install python2-decorator
dnf install gnome-session
dnf install perl-Data-OptList
dnf install libdmx
dnf install perl-File-HomeDir
dnf install fuse
dnf install libgpg-error
dnf install tar
dnf install cairo
dnf install chrpath
dnf install abrt-tui
dnf install gnupg
dnf install gstreamer-tools
dnf install perl-File-HomeDir
dnf install ilmbase
dnf install cracklib-dicts
dnf install python3-libxml2
dnf install libgcc
dnf install libblockdev-kbd
dnf install emacs-filesystem
dnf install python3-appdirs
dnf install libgweather
dnf install libpng-devel
dnf install liblangtag
dnf install perl-Sys-Syslog
dnf install hunspell
dnf install perl-Pod-Usage
dnf install kernel-modules
dnf install libcanberra-gtk3
dnf install xz
dnf install libfontenc-devel
dnf install libgweather-devel
dnf install cups-pk-helper
dnf install libnfnetlink
dnf install xdg-desktop-portal
dnf install perl-Locale-Maketext-Simple
dnf install libev
dnf install perl-Archive-Tar
dnf install selinux-policy
dnf install dbus-glib-devel
dnf install ghostscript-core
dnf install graphite2
dnf install libimagequant
dnf install ibus-m17n
dnf install pigz
dnf install libibverbs
dnf install gdbm
dnf install python3-cairo
dnf install python-keyczar
dnf install perl-PathTools
dnf install sssd-common-pac
dnf install openssl-libs
dnf install golang-github-bugsnag-bugsnag-go-devel
dnf install passwdqc-lib
dnf install gcc-gdb-plugin
dnf install perl-File-Temp
dnf install libtar
dnf install golang-github-stretchr-testify-devel
dnf install jasper-libs
dnf install passwdqc
dnf install libasyncns
dnf install ghc-srpm-macros
dnf install python3-pyOpenSSL
dnf install spice-vdagent
dnf install mc
dnf install libtimezonemap
dnf install oprofile
dnf install protobuf-c
dnf install python3-cssselect
dnf install xorg-x11-utils
dnf install libdap
dnf install thai-scalable-fonts-common
dnf install xalan-c
dnf install libgeotiff
dnf install python-sphinx-locale
dnf install clutter-gtk-devel
dnf install atlas
dnf install imsettings-gsettings
dnf install xorg-x11-xkb-utils
dnf install python3-pysocks
dnf install libutempter
dnf install ibus-hangul
dnf install rcs
dnf install itstool
dnf install libxkbfile
dnf install iagno
dnf install xz-devel
dnf install libgltf
dnf install ilmbase
dnf install speech-dispatcher-espeak
dnf install vconfig
dnf install libusb
dnf install sound-theme-freedesktop
dnf install lklug-fonts
dnf install dosfstools
dnf install gd
dnf install python-rhsm-certificates
dnf install perl-Carp
dnf install sqlite-libs
dnf install poppler-glib
dnf install libvpx
dnf install librtmp
dnf install gnome-calendar
dnf install libxcb
dnf install libmpcdec
dnf install rubygem-json
dnf install fedora-rpm-macros
dnf install bash-completion
dnf install libffi
dnf install perl-autodie
dnf install gzip
dnf install cyrus-sasl-md5
dnf install perl-Text-Unidecode
dnf install git
dnf install gnome-online-miners
dnf install libcanberra
dnf install smartmontools
dnf install krb5-devel
dnf install libxshmfence
dnf install python3-jsonschema
dnf install webkitgtk4-jsc
dnf install python3-iniparse
dnf install boost-wave
dnf install libgnome-keyring-devel
dnf install SDL
dnf install nss-sysinit
dnf install libhangul
dnf install libdnf
dnf install lua-json
dnf install alsa-ucm
dnf install libksba
dnf install ustr
dnf install qt
dnf install gmp-c++
dnf install grub2-efi
dnf install gtk2-engines
dnf install kf5-kio-doc
dnf install kernel
dnf install libXdamage-devel
dnf install gpm-libs
dnf install libkkc-data
dnf install xapian-core-devel
dnf install adobe-source-han-sans-cn-fonts
dnf install perl-Module-CoreList
dnf install libqzeitgeist
dnf install chrony
dnf install pam_pkcs11
dnf install nautilus-sendto
dnf install libgdata
dnf install qt5-qtwebchannel
dnf install imsettings
dnf install google-crosextra-carlito-fonts
dnf install PackageKit-gstreamer-plugin
dnf install gnome-abrt
dnf install perl-Params-Util
dnf install fwupdate-efi
dnf install enchant
dnf install ncurses-compat-libs
dnf install initscripts
dnf install pacman
dnf install libxklavier
dnf install pakchois
dnf install osinfo-db
dnf install lua-expat
dnf install perl-Thread-Queue
dnf install python3-caribou
dnf install libgnome-keyring
dnf install adwaita-icon-theme
dnf install psmisc
dnf install golang-github-coreos-pkg-devel
dnf install libcap-devel
dnf install popt-devel
dnf install pam-devel
dnf install f23-backgrounds-gnome
dnf install grilo
dnf install libuv
dnf install python3-dnf
dnf install perl-ExtUtils-MakeMaker
dnf install speex
dnf install libaio
dnf install strongswan
dnf install urw-fonts
dnf install bind-license
dnf install perl-Env
dnf install ImageMagick-libs
dnf install appstream
dnf install pinentry-gtk
dnf install kf5-kcompletion
dnf install libreoffice-langpack-en
dnf install device-mapper-multipath-libs
dnf install gtkmm24
dnf install device-mapper
dnf install golang-github-davecgh-go-spew-devel
dnf install strongswan-charon-nm
dnf install device-mapper-persistent-data
dnf install golang-github-Sirupsen-logrus-devel
dnf install ipw2200-firmware
dnf install c-ares
dnf install perl-libwww-perl
dnf install libsane-hpaio
dnf install libmpeg2
dnf install kf5-kglobalaccel
dnf install plymouth-core-libs
dnf install libical
dnf install xorg-x11-drv-fbdev
dnf install clutter-devel
dnf install qemu-block-gluster
dnf install libacl-devel
dnf install bluebird-xfwm4-theme
dnf install boost-filesystem
dnf install gzip
dnf install subversion-libs
dnf install gstreamer-devel
dnf install mesa-libgbm
dnf install mesa-libEGL-devel
dnf install systemd-udev
dnf install totem-nautilus
dnf install kf5-solid-libs
dnf install hyperv-daemons-license
dnf install python3-inotify
dnf install kernel-modules
dnf install fpaste
dnf install gts
dnf install harfbuzz-devel
dnf install xcb-util-keysyms
dnf install gnome-taquin
dnf install libudisks2
dnf install libzip
dnf install nm-connection-editor
dnf install perl-Perl-OSType
dnf install python3-enchant
dnf install python3-pyatspi
dnf install ntpdate
dnf install libXmu
dnf install network-manager-applet
dnf install perl-srpm-macros
dnf install rubygem-rdoc
dnf install mtools
dnf install kf5-kdeclarative
dnf install google-noto-sans-tai-tham-fonts
dnf install libblkid
dnf install iwl105-firmware
dnf install hwloc-libs
dnf install NetworkManager-libreswan-gnome
dnf install policycoreutils
dnf install breeze-cursor-theme
dnf install gdk-pixbuf2-modules
dnf install python2-sphinx_rtd_theme
dnf install perl-NTLM
dnf install realmd
dnf install archlinux-keyring
dnf install liberation-sans-fonts
dnf install perl-Module-Build
dnf install ocaml-srpm-macros
dnf install naver-nanum-fonts-common
dnf install cldr-emoji-annotation
dnf install caribou-gtk3-module
dnf install kbd-legacy
dnf install p11-kit-devel
dnf install rpm-build-libs
dnf install libquvi-scripts
dnf install librevenge
dnf install libfontenc
dnf install libspatialite
dnf install gdouros-symbola-fonts
dnf install unzip
dnf install ncurses-compat-libs
dnf install libogg-devel
dnf install f24-backgrounds-base
dnf install glibc-langpack-en
dnf install libsndfile
dnf install libreoffice-data
dnf install fedora-logos
dnf install libxslt-devel
dnf install rpmfusion-nonfree-appstream-data
dnf install libspectre
dnf install xmlsec1-openssl
dnf install clutter
dnf install libgfortran
dnf install libcap
dnf install lvm2-libs
dnf install dnf-automatic
dnf install gsoap
dnf install python2-paramiko
dnf install gawk
dnf install seabios-bin
dnf install python3-dnf-plugins-extras-common
dnf install NetworkManager-libreswan
dnf install python3-idna
dnf install xfce4-notifyd
dnf install perl-Pod-Checker
dnf install intltool
dnf install python2-pycurl
dnf install double-conversion
dnf install perl-ExtUtils-Command
dnf install kernel-core
dnf install liberation-fonts-common
dnf install gsettings-desktop-schemas
dnf install nautilus
dnf install hicolor-icon-theme
dnf install harfbuzz
dnf install perl-IO-Compress
dnf install pinfo
dnf install kmod-VirtualBox
dnf install libchamplain
dnf install khmeros-base-fonts
dnf install phonon-qt5
dnf install gupnp-dlna
dnf install perl-Digest-MD5
dnf install paratype-pt-sans-fonts
dnf install libev
dnf install python-gobject-base
dnf install lldpad
dnf install kwin-libs
dnf install libwsman1
dnf install pcsc-lite-devel
dnf install mactel-boot
dnf install libosinfo
dnf install NetworkManager-openconnect-gnome
dnf install tigervnc-license
dnf install protobuf
dnf install gcr-devel
dnf install libdrm-devel
dnf install dleyna-connector-dbus
dnf install liberation-mono-fonts
dnf install libXrender-devel
dnf install gupnp
dnf install perl-Data-OptList
dnf install paktype-naskh-basic-fonts
dnf install man-pages
dnf install irqbalance
dnf install iodine-client
dnf install Thunar
dnf install libarchive
dnf install qt5-qttools-common
dnf install libwebp
dnf install desktop-file-utils
dnf install libdmapsharing
dnf install pam-kwallet
dnf install perl-Email-Date-Format
dnf install perl-Pod-Parser
dnf install nspr-devel
dnf install xfce4-screenshooter
dnf install ibus-kkc
dnf install libXrandr
dnf install nodoka-filesystem
dnf install readline-devel
dnf install python3-iscsi-initiator-utils
dnf install GConf2
dnf install dtc
dnf install xorg-x11-apps
dnf install python3-dmidecode
dnf install libXpm
dnf install libblockdev-loop
dnf install copy-jdk-configs
dnf install basesystem
dnf install emacs-common
dnf install cgit
dnf install bc
dnf install ibus-libzhuyin
dnf install strace
dnf install gom
dnf install rygel
dnf install okular-part
dnf install telepathy-glib-vala
dnf install perl-Mozilla-CA
dnf install perl-Unicode-Normalize
dnf install elfutils
dnf install dhcp-common
dnf install libXvMC
dnf install xapian-core
dnf install colord
dnf install libsigsegv
dnf install mozjs24
dnf install libtevent
dnf install golang-github-bugsnag-panicwrap-devel
dnf install python3-enchant
dnf install dracut-network
dnf install akmod-VirtualBox
dnf install avahi-libs
dnf install libreofficekit
dnf install pakchois
dnf install bubblewrap
dnf install libmad
dnf install clucene09-core
dnf install naver-nanum-fonts-common
dnf install kernel
dnf install libsecret-devel
dnf install xorg-x11-drv-openchrome
dnf install libtommath
dnf install libvdpau
dnf install go-srpm-macros
dnf install python2-dnf-plugins-extras-common
dnf install pinentry
dnf install file-roller
dnf install xfce4-settings
dnf install iscsi-initiator-utils
dnf install color-filesystem
dnf install NetworkManager-vpnc-gnome
dnf install perl-JSON-PP
dnf install git-core
dnf install mpg123-plugins-jack
dnf install libsoup-devel
dnf install atk
dnf install libpath_utils
dnf install gns3-net-converter
dnf install albatross-xfwm4-theme
dnf install fprintd
dnf install docbook-dtds
dnf install libreport-plugin-systemd-journal
dnf install yelp
dnf install gvfs-goa
dnf install gtkmm30
dnf install libglvnd-gles
dnf install keybinder3
dnf install gnu-efi
dnf install libXinerama-devel
dnf install dracut
dnf install libselinux-python3
dnf install perl-XML-NamespaceSupport
dnf install webkitgtk4-plugin-process-gtk2
dnf install libXcomposite
dnf install tcpdump
dnf install fipscheck
dnf install kf5-kio-core
dnf install linux-atm
dnf install libutempter
dnf install NetworkManager-openconnect
dnf install ipcalc
dnf install unicode-ucd
dnf install libpng
dnf install nss-softokn-freebl-devel
dnf install ipset-libs
dnf install util-linux
dnf install libnotify
dnf install libsss_autofs
dnf install libXft
dnf install subunit-devel
dnf install qt5-qtdeclarative
dnf install cscope
dnf install perl-File-Listing
dnf install iwl4965-firmware
dnf install libattr
dnf install libselinux-python
dnf install gtk-murrine-engine
dnf install cronie
dnf install mcelog
dnf install perl-Perl-OSType
dnf install freetype-devel
dnf install python2-crypto
dnf install enchant
dnf install slang-devel
dnf install ibus-m17n
dnf install ogdi
dnf install libblockdev-crypto
dnf install oprofile
dnf install xfce4-about
dnf install policycoreutils-python3
dnf install python-ldap
dnf install perl-autodie
dnf install make
dnf install perl-Text-Diff
dnf install bubblewrap
dnf install hyphen-en
dnf install web-assets-filesystem
dnf install ibus
dnf install calc-stdrc
dnf install python-libxml2
dnf install expat-devel
dnf install acpica-tools
dnf install x264-libs
dnf install libXext-devel
dnf install gpg-pubkey
dnf install perl-CPAN-Meta
dnf install usb_modeswitch-data
dnf install gutenprint-libs
dnf install dhcp-common
dnf install rootfiles
dnf install kf5-kconfig-core
dnf install liberation-serif-fonts
dnf install libavc1394
dnf install libevent
dnf install bluebird-gtk2-theme
dnf install emacs
dnf install ocaml-srpm-macros
dnf install PyYAML
dnf install sssd-ldap
dnf install hplip-libs
dnf install docbook-style-dsssl
dnf install python-keyczar
dnf install gnome-session-wayland-session
dnf install libepoxy
dnf install okular
dnf install libatasmart
dnf install mpg123-libs
dnf install libvisual
dnf install appstream-data
dnf install ncurses
dnf install gnome-common
dnf install libwnck3
dnf install xfce4-appfinder
dnf install gnome-logs
dnf install libassuan
dnf install pyxattr
dnf install lsof
dnf install json-c
dnf install hypervfcopyd
dnf install cpuid
dnf install elfutils-libelf-devel
dnf install boost-regex
dnf install perl-Digest-MD5
dnf install docbook-dtds
dnf install python2-gpg
dnf install kf5-kbookmarks
dnf install file-libs
dnf install totem
dnf install imsettings
dnf install pyliblzma
dnf install libinput
dnf install bluez-cups
dnf install libgnome-keyring
dnf install libserf
dnf install pkgconf-pkg-config
dnf install python-httplib2
dnf install sane-backends
dnf install ccache
dnf install rest
dnf install hypervfcopyd
dnf install ghostscript-fonts
dnf install python2-nose
dnf install libreport-plugin-kerneloops
dnf install beignet
dnf install libimobiledevice
dnf install python-ldap
dnf install qt-settings
dnf install NetworkManager-ssh-gnome
dnf install libxml2
dnf install xen-libs
dnf install polkit-pkla-compat
dnf install usermode
dnf install python-ipaddress
dnf install acl
dnf install python2-pyparsing
dnf install libuser
dnf install perl-HTML-Parser
dnf install fedora-icon-theme
dnf install iwl1000-firmware
dnf install perl-Pod-Escapes
dnf install cairo-gobject-devel
dnf install mailx
dnf install kf5-kwayland
dnf install nano
dnf install docker-common
dnf install cheese-libs
dnf install perl-File-Which
dnf install libXxf86dga
dnf install telepathy-glib
dnf install libzhuyin
dnf install python3-dnf-plugins-core
dnf install rodent-icon-theme
dnf install libXtst
dnf install clutter-devel
dnf install attr
dnf install gnome-tetravex
dnf install poppler
dnf install libcacard
dnf install wireless-tools
dnf install liblangtag-data
dnf install nettle
dnf install perl-Class-ISA
dnf install which
dnf install webkitgtk4-devel
dnf install libXfixes-devel
dnf install jomolhari-fonts
dnf install lohit-kannada-fonts
dnf install NetworkManager-openvpn
dnf install gutenprint-cups
dnf install libreoffice-opensymbol-fonts
dnf install glibc
dnf install ghostscript-x11
dnf install rsync
dnf install cryptopp
dnf install golang-github-stretchr-objx-devel
dnf install ibus-kkc
dnf install python3-sip
dnf install zlib
dnf install sssd-ipa
dnf install dejavu-sans-mono-fonts
dnf install perl-TermReadKey
dnf install libpng12
dnf install js
dnf install libnetfilter_conntrack
dnf install bash
dnf install libvisual
dnf install libSM
dnf install libsemanage
dnf install libmms
dnf install gnu-free-fonts-common
dnf install perl-podlators
dnf install pcre2
dnf install fedora-user-agent-chrome
dnf install python2-snowballstemmer
dnf install perl-B-Lint
dnf install gnome-sudoku
dnf install greybird-gtk3-theme
dnf install mousetweaks
dnf install flatpak-libs
dnf install dejavu-fonts-common
dnf install libsemanage-python3
dnf install pcmciautils
dnf install kf5-kiconthemes
dnf install libglvnd-egl
dnf install appstream-qt
dnf install libicu-devel
dnf install sos
dnf install python3-multidict
dnf install libproxy
dnf install boost-python
dnf install PackageKit-glib
dnf install control-center-filesystem
dnf install libgdither
dnf install perl-Digest
dnf install recordmydesktop
dnf install perl-Storable
dnf install httpd-tools
dnf install python2-mock
dnf install sgabios-bin
dnf install golang-google-golang-api-devel
dnf install golang-googlecode-goprotobuf-devel
dnf install linux-firmware
dnf install iodine-client
dnf install libXt
dnf install libkkc-common
dnf install kdegraphics-mobipocket
dnf install setools-python
dnf install kmod-VirtualBox
dnf install util-linux-user
dnf install NetworkManager-ssh
dnf install passwdqc-lib
dnf install fedora-repos-rawhide
dnf install iwl6050-firmware
dnf install libxcb-devel
dnf install openssh-server
dnf install tracker
dnf install libXpm
dnf install libpeas
dnf install expat-devel
dnf install python3-pid
dnf install python3-dmidecode
dnf install system-config-printer-libs
dnf install mc
dnf install gamin
dnf install gnome-settings-daemon
dnf install perl-Sub-Exporter
dnf install perl-MIME-Lite
dnf install lightdm-gobject
dnf install fros
dnf install dmraid-events
dnf install foomatic-db-ppds
dnf install jwhois
dnf install python3-pyparsing
dnf install libmng
dnf install libnghttp2
dnf install golang-gopkg-yaml-devel
dnf install python3-augeas
dnf install libref_array
dnf install perl-Net-Ping
dnf install libxkbfile
dnf install fedora-icon-theme
dnf install f25-backgrounds-gnome
dnf install perl-Class-ISA
dnf install gettext-devel
dnf install perl-Data-Section
dnf install libgomp
dnf install expat
dnf install sssd-common
dnf install mod_dnssd
dnf install f25-backgrounds-gnome
dnf install kf5-knotifications
dnf install libXres
dnf install gtk-doc
dnf install device-mapper-event-libs
dnf install vpnc
dnf install libfastjson
dnf install lua-socket
dnf install gnome-calculator
dnf install hunspell-en-GB
dnf install xorg-x11-drv-wacom
dnf install ipxe-roms-qemu
dnf install perl-Text-Soundex
dnf install perl-PathTools
dnf install virt-top
dnf install gutenprint-cups
dnf install gnome-bluetooth-libs
dnf install xfwm4-themes
dnf install opus
dnf install libsamplerate
dnf install gnome-screenshot
dnf install libproxy
dnf install gtk3-devel-docs
dnf install golang-golangorg-net-devel
dnf install bzip2
dnf install ipset
dnf install dhcp-libs
dnf install libini_config
dnf install gstreamer1-plugins-base
dnf install dosfstools
dnf install libpciaccess
dnf install kf5-kidletime
dnf install gpg-pubkey
dnf install gvfs-archive
dnf install neon
dnf install at-spi2-core
dnf install gnome-robots
dnf install yelp-xsl
dnf install gpsd-libs
dnf install cups-libs
dnf install libproxy-mozjs
dnf install gns3-net-converter
dnf install oxygen-fonts-common
dnf install folks
dnf install samba-common-libs
dnf install golang-github-Sirupsen-logrus-devel
dnf install libXext-devel
dnf install filesystem
dnf install libreport-plugin-reportuploader
dnf install qrencode-libs
dnf install nodejs-emojione-json
dnf install compat-openssl10
dnf install libgepub
dnf install libglvnd-core-devel
dnf install perl-SGMLSpm
dnf install xorg-x11-server-Xwayland
dnf install gtk-murrine-engine
dnf install device-mapper-multipath
dnf install libkadm5
dnf install NetworkManager-ssh-gnome
dnf install startup-notification
dnf install iwl3945-firmware
dnf install google-noto-sans-tagalog-fonts
dnf install qt5-qttools-libs-help
dnf install kde-filesystem
dnf install xfce4-about
dnf install irqbalance
dnf install python3-requests-ftp
dnf install perl-Pod-Usage
dnf install hunspell
dnf install libcroco
dnf install foomatic-db
dnf install abrt-addon-python3
dnf install gtk-xfce-engine
dnf install perl-local-lib
dnf install perl-Text-Diff
dnf install dejavu-serif-fonts
dnf install python3-cssselect
dnf install glade-libs
dnf install libzhuyin
dnf install libref_array
dnf install ibus-wayland
dnf install frei0r-plugins
dnf install poppler-data
dnf install libexttextcat
dnf install libtool
dnf install python3-javapackages
dnf install google-android-emoji-fonts
dnf install python2-pyOpenSSL
dnf install hplip
dnf install sil-abyssinica-fonts
dnf install hardlink
dnf install ipcalc
dnf install gnu-free-serif-fonts
dnf install libquadmath
dnf install kf5-ki18n
dnf install comps-extras
dnf install mesa-filesystem
dnf install perl-HTML-Parser
dnf install gpsd-libs
dnf install liberation-fonts-common
dnf install mock
dnf install dleyna-connector-dbus
dnf install perl-File-Slurp
dnf install djvulibre-libs
dnf install python2-crypto
dnf install perl-Text-ParseWords
dnf install npth
dnf install selinux-policy-targeted
dnf install libnl3
dnf install python3-blockdev
dnf install libvorbis
dnf install glade-libs
dnf install libdb-utils
dnf install linux-atm
dnf install tzdata-java
dnf install colord-gtk
dnf install kf5-kdoctools
dnf install imvirt
dnf install kf5-plasma
dnf install perl-HTTP-Tiny
dnf install mdadm
dnf install xorg-x11-drv-vmware
dnf install gnome-documents-libs
dnf install openconnect
dnf install libidn2
dnf install kf5-kwallet-libs
dnf install perl-ExtUtils-MakeMaker
dnf install boost-graph
dnf install python3-pip
dnf install snappy
dnf install iptables-libs
dnf install bcache-tools
dnf install libdvdnav
dnf install libssh2
dnf install pkgconf-m4
dnf install python2-jinja2
dnf install google-android-emoji-fonts
dnf install appstream-qt
dnf install bzip2
dnf install libreport-web
dnf install redhat-lsb-submod-security
dnf install opencl-filesystem
dnf install btrfs-progs
dnf install m4
dnf install libXrandr-devel
dnf install crypto-policies
dnf install skopeo-containers
dnf install opensp
dnf install desktop-file-utils
dnf install elfutils-libelf
dnf install python3-sssdconfig
dnf install glibmm24
dnf install lvm2
dnf install fedora-productimg-workstation
dnf install kde-filesystem
dnf install libgcrypt
dnf install PackageKit-gtk3-module
dnf install gnome-themes
dnf install libnotify
dnf install qt5-qtwebsockets
dnf install ebook-tools-libs
dnf install perl-Getopt-Long
dnf install argyllcms
dnf install libmbim-utils
dnf install zlib-devel
dnf install abrt-addon-ccpp
dnf install hyperv-daemons-license
dnf install firewalld-filesystem
dnf install epiphany-runtime
dnf install perl-IPC-Cmd
dnf install pytz
dnf install perl-Package-Generator
dnf install python-systemd-doc
dnf install lm_sensors-libs
dnf install cairo-devel
dnf install postfix
dnf install gnome-mahjongg
dnf install libpciaccess
dnf install mailcap
dnf install nodoka-filesystem
dnf install patchutils
dnf install golang-github-coreos-go-systemd-devel
dnf install setup
dnf install evince-libs
dnf install libexif
dnf install mailcap
dnf install symlinks
dnf install paps
dnf install perl-ExtUtils-ParseXS
dnf install python3-rpm
dnf install perl-threads
dnf install python-mako
dnf install perl-Text-Template
dnf install mallard-rng
dnf install libxcb-devel
dnf install perl-Unicode-EastAsianWidth
dnf install microcode_ctl
dnf install perl-Exporter
dnf install vte291
dnf install dmidecode
dnf install perl-IPC-Cmd
dnf install libreoffice-core
dnf install bzip2-devel
dnf install libmpc
dnf install perl-Time-Local
dnf install libdnet
dnf install lz4
dnf install kf5-sonnet-core
dnf install apr
dnf install libseccomp
dnf install fedora-release-notes
dnf install perl-Pod-Plainer
dnf install xfce4-places-plugin
dnf install popt
dnf install python2-pygpgme
dnf install SDL_image
dnf install lohit-devanagari-fonts
dnf install perl-Digest
dnf install kmod-VirtualBox
dnf install libmpcdec
dnf install dos2unix
dnf install greybird-gtk2-theme
dnf install gnome-disk-utility
dnf install policycoreutils-python-utils
dnf install perl-Module-Load
dnf install perl-ExtUtils-Manifest
dnf install libglvnd-glx
dnf install dracut-live
dnf install memtest86+
dnf install perl-Net-HTTP
dnf install mesa-libglapi
dnf install ansible
dnf install python2-iniparse
dnf install boost-program-options
dnf install samba-client-libs
dnf install gsound
dnf install opusfile
dnf install python2-devel
dnf install python-IPy
dnf install smc-fonts-common
dnf install libreport-filesystem
dnf install cups
dnf install libXrandr
dnf install xorg-x11-drv-ati
dnf install freetype
dnf install golang-github-docker-libcontainer-devel
dnf install ntfsprogs
dnf install gamin
dnf install lockdev-devel
dnf install atk-devel
dnf install qt5-qtbase-common
dnf install gtk2-engines
dnf install readline
dnf install iwl6000g2b-firmware
dnf install python2-hawkey
dnf install libvirt-libs
dnf install libsecret-devel
dnf install libspatialite
dnf install libthai
dnf install python-magic
dnf install mtools
dnf install python3-zipstream
dnf install abrt-python3
dnf install tcp_wrappers-libs
dnf install libraw1394
dnf install f26-backgrounds-gnome
dnf install perl-Module-Find
dnf install system-config-printer-udev
dnf install dmraid
dnf install perl-HTML-Tagset
dnf install gstreamer
dnf install libgphoto2
dnf install libidn
dnf install pango
dnf install libunicap
dnf install perl-Compress-Bzip2
dnf install libattr-devel
dnf install speech-dispatcher
dnf install gsm
dnf install rpm-plugin-systemd-inhibit
dnf install autoconf
dnf install foomatic-db-filesystem
dnf install libXfont2-devel
dnf install sgpio
dnf install f25-backgrounds-base
dnf install libotf
dnf install edk2-ovmf
dnf install dejavu-sans-fonts
dnf install python2-librepo
dnf install python3-slip
dnf install cups-filters-libs
dnf install perl-Software-License
dnf install wpa_supplicant
dnf install kf5-karchive
dnf install libusbx
dnf install perl-MIME-Lite
dnf install libatomic_ops
dnf install libndp
dnf install sssd-proxy
dnf install libiscsi
dnf install python2-dnf
dnf install libgnome-keyring-devel
dnf install guile
dnf install libmbim-utils
dnf install proj
dnf install evolution-data-server-devel
dnf install NetworkManager-pptp-gnome
dnf install xvidcore
dnf install python2-rpm-macros
dnf install pixman
dnf install python2-ply
dnf install gnome-common
dnf install lohit-odia-fonts
dnf install kernel-modules
dnf install gstreamer1
dnf install gdk-pixbuf2-xlib
dnf install libmcpp
dnf install SDL2
dnf install hplip
dnf install harfbuzz-icu
dnf install libstemmer
dnf install perl-Compress-Raw-Bzip2
dnf install system-python
dnf install efivar
dnf install python3-cups
dnf install gdb-headless
dnf install sni-qt
dnf install python3-cryptography
dnf install ntfs
dnf install lato-fonts
dnf install perl-XML-Parser
dnf install usbredir
dnf install protobuf-compiler
dnf install nss-devel
dnf install kf5-kactivities-libs
dnf install libgcrypt-devel
dnf install libmnl
dnf install cairomm
dnf install fleet-devel
dnf install gnupg2-smime
dnf install check-devel
dnf install device-mapper-libs
dnf install NetworkManager-iodine
dnf install at-spi2-atk-devel
dnf install osinfo-db-tools
dnf install qt5-qttools-libs-clucene
dnf install avahi-autoipd
dnf install color-filesystem
dnf install mythes
dnf install gupnp-dlna
dnf install libXmu
dnf install ca-certificates
dnf install nettle
dnf install plasma-breeze-common
dnf install libmount
dnf install perl-XML-NamespaceSupport
dnf install libblockdev-utils
dnf install hunspell-en-US
dnf install libva
dnf install libreport-python3
dnf install libXdamage
dnf install python3-libcomps
dnf install perl-CPAN-Meta-YAML
dnf install unixODBC
dnf install clucene-contribs-lib
dnf install fribidi
dnf install pam_krb5
dnf install xorg-x11-fonts-misc
dnf install libblockdev-lvm
dnf install libzhuyin-data
dnf install libvorbis-devel
dnf install gnome-online-accounts
dnf install dracut-live
dnf install python-IPy
dnf install perl-File-CheckTree
dnf install radare2
dnf install perl-Pod-Parser
dnf install libdmapsharing
dnf install stoken-libs
dnf install okular-libs
dnf install checkpolicy
dnf install libXScrnSaver
dnf install telepathy-glib-devel
dnf install abrt-gui
dnf install libwnck
dnf install kf5-kwidgetsaddons
dnf install openal-soft
dnf install perl-Fedora-VSP
dnf install dhcp-client
dnf install python3-pyasn1
dnf install libpwquality
dnf install libreoffice-gtk2
dnf install nspr
dnf install libmtp
dnf install VirtualBox
dnf install lm_sensors
dnf install oxygen-mono-fonts
dnf install jsoncpp
dnf install gnutls
dnf install evince-djvu
dnf install arch-install-scripts
dnf install perl-ExtUtils-ParseXS
dnf install libatomic
dnf install yum
dnf install apr-util
dnf install compat-libwebp05
dnf install libzapojit
dnf install ruby-libs
dnf install perl-IO
dnf install gpg-pubkey
dnf install perl-MRO-Compat
dnf install boost-locale
dnf install garcon
dnf install perl-libnet
dnf install libkkc
dnf install openssh
dnf install libde265
dnf install systemtap-sdt-devel
dnf install hfsplus-tools
dnf install setuptool
dnf install gfbgraph
dnf install python-ipaddress
dnf install gpg-pubkey-fdb19c98
dnf install iproute
dnf install mpage
dnf install ModemManager-glib
dnf install liba52
dnf install libksba
dnf install redhat-lsb-submod-multimedia
dnf install pacman-filesystem
dnf install golang-google-golang-api-devel
dnf install libXinerama
dnf install pocl
dnf install adwaita-gtk2-theme
dnf install kf5-khtml
dnf install hfsplus-tools
dnf install python2-cryptography
dnf install yum-utils
dnf install ipset
dnf install NetworkManager-strongswan-gnome
dnf install redhat-lsb-desktop
dnf install docbook-style-xsl
dnf install perl-Text-Glob
dnf install albatross-gtk3-theme
dnf install libglade2
dnf install libX11
dnf install avahi-glib
dnf install basesystem
dnf install createrepo_c
dnf install NetworkManager-adsl
dnf install keyrings-filesystem
dnf install ppp
dnf install indent
dnf install python3-pytz
dnf install libXft-devel
dnf install dwz
dnf install avahi-libs
dnf install python2-systemd
dnf install perl-Sub-Exporter
dnf install lm_sensors
dnf install libgdata-devel
dnf install rasqal
dnf install pcsc-lite-devel
dnf install rsyslog
dnf install coreutils-common
dnf install libmodman
dnf install python2-rpm
dnf install python2-pyasn1
dnf install perl-IO-Zlib
dnf install julietaula-montserrat-fonts
dnf install perl-Test-Simple
dnf install dnf-plugins-extras-common-data
dnf install pigz
dnf install f25-backgrounds-base
dnf install c-ares
dnf install python3-olefile
dnf install libpng
dnf install libreoffice-ure
dnf install perl-ExtUtils-CBuilder
dnf install ibus-rawcode
dnf install libproxy-mozjs
dnf install xml-security-c
